---
kind: pipeline
name: rpi-base-image

steps:
- name: build
  image: plugins/docker
  settings:
    repo: foexle/rpi-img-builder
    tags: latest

- name: create
  image: foexle/rpi-img-builder:latest
  environment:
    PACKERFILE: packer/rpi-base.json
  volumes:
  - name: image
    path: /images/

volumes:
- name: image
  host:
    path: /tmp/images/


